/*
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class XDSLUiModule extends AbstractXDSLUiModule {
}
