/*
 * generated by Xtext 2.40.0.M3
 */
package eu.extremexp.dsl.validation

import org.eclipse.xtext.validation.Check
import eu.extremexp.dsl.xDSL.Reference
import eu.extremexp.dsl.xDSL.Experiment
import org.eclipse.emf.common.util.URI
import eu.extremexp.dsl.xDSL.XDSLPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class XDSLValidator extends AbstractXDSLValidator {
	
	public static val INVALID_FILE = 'cannotFindFile'

	@Check
	def checkRefFileExist(Reference refObj) {
		val path = refObj.ref
		if (path !== null && !path.trim.empty){
			val experiment = refObj.eContainer as Experiment
			val baseURI =experiment.eResource.URI
			if (baseURI.platform){
				val projectName = baseURI.segment(1)
				val fileURI = URI.createPlatformResourceURI(projectName + "/" + path, true)
				try{
					var resource = experiment.eResource.resourceSet.getResource(fileURI, true)
				}
				catch (Exception e){
					warning('Cannot find file ' + refObj.ref , 
					XDSLPackage.Literals.REFERENCE__REF,
					INVALID_FILE)
				}
			}
		}
	}	
}
