/*
 * generated by Xtext 2.36.0
 */
package eu.extremexp.dsl.validation

import org.eclipse.xtext.validation.Check
import eu.extremexp.dsl.xDSL.Workflow
import eu.extremexp.dsl.xDSL.XDSLPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class XDSLValidator extends AbstractXDSLValidator {
	
	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					XDSLPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

//	// TODO enforce acyclic reference to not happen
//	@Check
//	def checkAcyclic(Workflow wf){
//		if (wf.name == "aw"){
//			error("some error", XDSLPackage.Literals.WORKFLOW__NAME, INVALID_NAME)
//		}
//	}
}
