/*
 * generated by Xtext 2.32.0
 */
package eu.extremexp.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XDSLRuntimeModule extends AbstractXDSLRuntimeModule {
}
