grammar eu.extremexp.dsl.XDSL with org.eclipse.xtext.common.Terminals

generate xDSL "http://www.extremexp.eu/dsl/XDSL"

Root:
	'package' name=ID ';'
	workflows += Workflow*
	
;

// workflow is an abstract class that can be extended by the following classes
Workflow:
	CompositeWorkflow | TaskSpecification | AssembledWorflow
;



CompositeWorkflow:
	'workflow' name=ID '{'
		(
			// shared members (i.e. super members)
			inputs += InputData			|
			outputs += OutputData 
			// now
		)*
	'}'
;

AssembledWorflow:
	'workflow' name=ID 'from' parent=[Workflow] '{'
		(
			// shared members (i.e. super members)
			inputs += InputData			|
			outputs += OutputData 		|
			
			substitutedTask += SubstitutedTask
		)*
	'}'
;

TaskSpecification:
	'task' name=ID '{'
		(
			// shared members (i.e. super members)
			inputs += InputData			|
			outputs += OutputData 
		)*
	'}'
;

Node:
	Task | Event
;

// Whatever can be linked but not necessary allowing instantiation 
LinkableNode:
	Node | Operator
;


// Data
InputData:
	'define' 'input' 'data' name=ID ';' 
;

OutputData:
	'define' 'output' 'data' name=ID ';' 
;


// Task
SubstitutedTask:
	'configure' task=Task
;

Task:
	(abstract?= 'define' 'task' name=ID ';')
	|
	// TODO if a task is directly configured without given name, should we allow it?
	('configure' 'task' task=[Task|ID] '{'
		(
			// shared members (i.e. super members)
			inputs += InputData			|
			outputs += OutputData 		|	
			
			// special members
			metadata += MetaData		|
			
			// single members
			'description' description=STRING ';'		|
			'implementation' primitiveImplementation=STRING ';'		

		)*
		
	'}')
;

MetaData:
	'{' name=STRING ':' value=STRING '}' ';'
;

// Event
Event:
	eventValue=EventValue	
;

enum EventValue:
	START='START' | END='END'
;


// Operator
Operator:
	Join | Parallel | Exclusive | Inclusive 
;


Join :
	'JOIN-'  name=ID 
;

Parallel :
	'PARALLEL-' name=ID 
;
Exclusive :
	'EXCLUSIVE-' name=ID  
;

Inclusive :
	'INCLUSIVE-' name=ID  
;

// Link
Link:
	ConditionalLink | RegularLink | ExceptionalLink
;


ConditionalLink:
	input=[LinkableNode] '?->' output=[LinkableNode] '{'
		"condition" condition=STRING ';'
	'}'
;

RegularLink:
	input=[LinkableNode] '-->' output=[LinkableNode] ';'
;

ExceptionalLink:
	input=[LinkableNode] '!->' output=[LinkableNode] '{'
		"event" event=STRING ';'
	'}'
;
