/*
 * generated by Xtext 2.37.0-SNAPSHOT
 */
package eu.extremexp.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XDSLStandaloneSetup extends XDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new XDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
