grammar eu.extremexp.dsl.XDSL with org.eclipse.xtext.common.Terminals

generate xDSL "http://www.extremexp.eu/dsl/XDSL"

Root:
	(asPackage?= 'package' name=ID ';')?
	(
		workflows += Workflow		|
		groups += Group				|
		parameterTypes += ParameterType
	)* 
	
;

// workflow is an abstract class that can be extended by the following classes
Workflow:
	CompositeWorkflow | TaskSpecification | AssembledWorflow
;



CompositeWorkflow:
	'workflow' name=ID '{'
		(
			// shared members (i.e. super members)
			inputs += InputData						|	
			outputs += OutputData					| 
			
			// dedicated members
			dataConfigurations += DataConfiguration	|
			links += Link							|
			dataLinks += DataLink					|
			nodes += Node
		)*
	'}'
;

AssembledWorflow:
	'workflow' name=ID 'from' parent=[Workflow] '{'
		(
			// shared members (i.e. super members)
			inputs += InputData			|
			outputs += OutputData 		|
			
			// dedicated members
			substitutedTask += SubstitutedTask
		)*
	'}'
;

TaskSpecification:
	'task' name=ID '{'
		(
			// shared members (i.e. super members)
			inputs += InputData			|
			outputs += OutputData		| 		
			
			// dedicated members
			metrics += Metric			|
			parameters += Parameter 
		)*
	'}'
;

Node:
	Task | Event 
;


// Data
Data:
	InputData | OutputData
;
InputData:
	'define' 'input' 'data' name=ID ';' 
;

OutputData:
	'define' 'output' 'data' name=ID ';' 
;


DataConfiguration:
	'configure' 'data' data=[Data] '{'
		'path' path=STRING ';'
	'}'
;


// Task
SubstitutedTask:
	'configure' task=Task
;

Task:
	(abstract?= 'define' 'task' name=ID ';')
	|
	// TODO if a task is directly configured without given name, should we allow it?
	('configure' 'task' task=[Task|ID] '{'
		(
			// shared members (i.e. super members)
			inputs += InputData			|
			outputs += OutputData 		|	
			
			// special members
			('metadata''{' 	metadata +=MetaData (',' metadata +=MetaData)	 '}' )|
			
			// single members
			'description' description=STRING ';'		|
			'implementation' primitiveImplementation=STRING ';'		

		)*
		
	'}')
;

MetaData:
	name=STRING ':' value=STRING
;

// Event
Event:
	eventValue=EventValue	
;

enum EventValue:
	START='START' | END='END'
;


// Operator
Operator:
	Join | Parallel  | Exclusive | Inclusive 
;


terminal JOIN_TERM:
	'JOIN-'INT
;

terminal PARALLEL_TERM:
	'PARALLEL-'INT
;

terminal EXCLUSIVE_TERM:
	'EXCLUSIVE-'INT
;

terminal INCLUSIVE_TERM:
	'INCLUSIVE-'INT
;

Join :
    id=JOIN_TERM
 ;

Parallel :
	id=PARALLEL_TERM
;
Exclusive :
	id=EXCLUSIVE_TERM  
;

Inclusive :
	id=INCLUSIVE_TERM 
;


// Link
Link:
	ConditionalLink | RegularLink | ExceptionalLink
;


ConditionalLink:
	input=[Node] '?->' output=[Node] '{'
		(
			"condition" condition=STRING ';'	|
			"cases" cases+=Case+ 
		)
	'}'
;

RegularLink:
	input=[Node] '->' output=[Node] ';'
;

ExceptionalLink:
	input=[Node] '!->' output=[Node] '{'
		"event" event=STRING ';'
	'}'
;

Case: 
	case=STRING target=[Node] ';'
;
QualifiedName:
    ID ('.' ID)*
;

DataConnection:
	OutputData | InputData | Task
;

// DataLink
DataLink:
	(inputData=[DataConnection|QualifiedName] '-->' outputData=[DataConnection|QualifiedName]';')
;

// Parameter and Metric
Parameter:
	'param' name=ID '{'
		(
			('type' type=ParameterType ';')? 	&
			('default' defaultValue=STRING ';')? &
			('constraint' valueConstraint=STRING ';')? 
			
		) 
	'}'
;

Metric:
	'metric' name=ID '{'
		(
			('type' type=ParameterType ';')? &
			('kind' kind=MetricKind ';')? 
		)
	'}'
;

enum MetricKind:
	Series | Scalar
;

// GROUP
Group:
	'group' name=ID '{'
		tasks += Task
	'}'
;

//ParameterType

ParameterType:
	Structure | PrimitiveType | Array
;

Structure:
	'struct' name=ID '{'
		fields += Field ';'
	'}'
;

Field:
	name=ID ('as' type=ParameterType)?
;

Array:
	name=ID '['length=INT']' ('as' type=ParameterType)?
;

PrimitiveType returns ParameterType:
	{PrimitiveType} ('Integer' | 'Boolean' | 'String' | 'Blob')
;
