/*
 * generated by Xtext 2.32.0
 */
package eu.extremexp.dsl.ide

import com.google.inject.Guice
import eu.extremexp.dsl.LanguageRuntimeModule
import eu.extremexp.dsl.LanguageStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class LanguageIdeSetup extends LanguageStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new LanguageRuntimeModule, new LanguageIdeModule))
	}
	
}
