/*
 * generated by Xtext 2.32.0
 */
package eu.extremexp.dsl.scoping

import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.EReference
import org.eclipse.xtext.scoping.Scopes
import eu.extremexp.dsl.language.WorkflowInterface
import org.eclipse.xtext.EcoreUtil2
import eu.extremexp.dsl.language.AssembledWorkflow
import eu.extremexp.dsl.language.Workflow
import eu.extremexp.dsl.language.TaskConfiguration
import eu.extremexp.dsl.language.LanguagePackage
import eu.extremexp.dsl.language.Namespace

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
 

 
class LanguageScopeProvider extends AbstractLanguageScopeProvider  {

	def findNamespace(EObject obj){
		var ns = obj
		while (!(ns instanceof Namespace)){
			ns = ns.eContainer
		}
		
		return ns as Namespace
	}

 	/*
 	 * Finds the full Workflow (not assembled)
 	 * There are basically two paths:
 	 * 1- inside an assembled workflow and to move up we reach at workflow
 	 * 2- inside any other element and to move up we reach at the container 
 	 */
	def findFullWorkflow (EObject any){
		var element = any
		while (element != null && !(element instanceof Workflow)){
	
			if (element instanceof AssembledWorkflow){
				element = element.workflow
			}
			else {
				element = element.eContainer
			}
		}
		return element
	}
 	
	/*
 	 * Finds all tasks there is for a given workflow/assembled workflow 
 	 */
 	def findTasksOfWorkflowInterface (WorkflowInterface wi){
 		var wf = wi
 		while (!(wf instanceof Workflow)){
 			if (wf instanceof AssembledWorkflow){
 				wf = wf.workflow
 			}
 			else{
 				return newArrayList
 			}
 		}
 		return (wf as Workflow).tasks
 		
 	}
 	
 	/*
     * For task configuration we are interested is the following possible references
     * 1- Tasks of the "my" workflow
     * 2- Tasks of the [full] workflow "my" workflow assembled from
     * 3- If "I" am part of task configuration, then:
     *  3-a all above tasks  (that are not yet configured?)
     *  3-b all tasks of the implemented workflows
     * 
     */
 	def scopeTaskConfigurations(EObject context, EReference reference){
 		
         
    	// 1- is automatically resolved with 2
    	// 2- First we need to get the [Full] Workflow
    	var fullWorkflow = findFullWorkflow(context)
    	
    	if (fullWorkflow == null){
    		return null
    	}
    	
    	// list of tasks
    	var tasks = (fullWorkflow as Workflow).tasks
    	
    	// 3- is automatically resolved with 2
    	var container = context.eContainer
    	while (container instanceof TaskConfiguration){
    		var impl = container.implementation
    		if (impl != null && impl.workflow != null){
    			tasks += findTasksOfWorkflowInterface(impl.workflow)
    		} 
    		container = container.eContainer
    	}

    	return Scopes.scopeFor(tasks)
 	}
 	
 	
 	/*
 	 * Finds all data there is for a given workflow/assembled workflow 
 	 */
 	def findDataOfWorkflowInterface (WorkflowInterface wi){
 		var wf = wi
 		while (!(wf instanceof Workflow)){
 			if (wf instanceof AssembledWorkflow){
 				wf = wf.workflow
 			}
 			else{
 				return newArrayList
 			}
 		}
 		return (wf as Workflow).data
 		
 	}
 	
 	
 	
 	/*
     * For data configuration we are interested is the following possible references
     * 1- data of the "my" workflow
     * 2- data of the [full] workflow "my" workflow assembled from
     * 3- If "I" am part of task configuration, then:
     *  3-a all above data (that are not yet configured?)
     *  3-b all data of the implemented workflows
     * 
     */
 	def scopeDataConfiguration(EObject context, EReference reference){

         
    	// 1- is automatically resolved with 2
    	// 2- First we need to get the [Full] Workflow
    	var fullWorkflow = findFullWorkflow(context)
    	
    	if (fullWorkflow == null){
    		return null
    	}
    	
    	// list of tasks
    	var data = (fullWorkflow as Workflow).data
    	
    	// 3- is automatically resolved with 2
    	var container = context.eContainer
    	while (container instanceof TaskConfiguration){
    		var impl = container.implementation
    		if (impl != null && impl.workflow != null){
    			data += findDataOfWorkflowInterface(impl.workflow)
    		} 
    		container = container.eContainer
    	}

    	return Scopes.scopeFor(data)
 	}
 	
 	 
 	 /*
     * For setting params we are looking into three main parts
     * 1- data of the "my" workflow
     * 2- data of the [full] workflow "my" workflow assembled from
     * 3- if I am part of task configuration, then find"
     *  3-a all above params 
     *  3-b implementation workflow params 
     */
 	def scopeParam(EObject context, EReference reference){

         
    	// 1- is automatically resolved with 2
    	// 2- First we need to get the [Full] Workflow
    	var fullWorkflow = findFullWorkflow(context)
    	
    	
    	if (fullWorkflow == null){
    		return null
    	
    	}
    	// list of tasks
    	var params = (fullWorkflow as Workflow).params
    	
    	
    	var tc = context.eContainer
    	while (tc instanceof TaskConfiguration){
    		params += tc.params
    		if (tc.implementation != null){
    			var tcw = tc.implementation.workflow
    			if (tcw instanceof Workflow){
    				params += tcw.params
    			} 
    		}
    		tc = tc.eContainer
    		 
    	}
    	

    	return Scopes.scopeFor(params)
 	}
 	
 	
 	def findScope(EObject context, EReference reference) {

		/*
		 * TODO probably it is a good idea to separate the scope for implementation 
		 * and the actual assembly. But at this moment, they behave same.
		 */
		if (reference == LanguagePackage.Literals.ASSEMBLED_WORKFLOW__WORKFLOW
			|| reference == LanguagePackage.Literals.IMPLEMENTATION__WORKFLOW){
        	val found = super.getScope(context, reference)
        	if (found != null){
        		val resolvedWorkflows = newArrayList
				found.allElements.forEach[ element |
					val wf = element.EObjectOrProxy
					// find the resolved workflows except itself
					if (wf !== context)
						if (wf.eIsProxy){
							if (context.eResource.resourceSet != null){
								
								var createdWorkflow = EcoreUtil2.resolve(
									wf, context.eResource.resourceSet)
									
								var nsContext = findNamespace(context)
								var nsReference = findNamespace(createdWorkflow)	
								// TODO checking by the name, it can be confusing
								
								if	(nsContext instanceof Namespace && nsReference instanceof Namespace){
									if (nsContext.name == nsReference.name){
										resolvedWorkflows += createdWorkflow
									}
								}							
							}
						}
						
					else {
						resolvedWorkflows += wf
					}
				]

				return Scopes.scopeFor(resolvedWorkflows) 
        	}
        
        }

        if (reference == LanguagePackage.Literals.TASK_CONFIGURATION__TASK){
        	val found = scopeTaskConfigurations(context, reference)
        	if (found != null){
        		return found
        	}
        
        }
        
        if (reference == LanguagePackage.Literals.DATA_CONFIGURATION__DATA){
        	val found = scopeDataConfiguration(context, reference)
        	if (found != null){
        		return found
        	}
        
        }
        
       if (reference == LanguagePackage.Literals.DATA__OTHER_DATA){
        	val found = scopeDataConfiguration(context, reference)
        	if (found != null){
        		return found
        	}
        
        }
        
        if (reference == LanguagePackage.Literals.PARAM_SET__OTHER_PARAM ||
        	reference == LanguagePackage.Literals.PARAM_SET__PARAM ||
        	reference == LanguagePackage.Literals.PARAM__OTHER_PARAM){
        	val found = scopeParam(context, reference)
        	if (found != null){
        		return found
        	}
        
        }

        return super.getScope(context, reference)
    }
    
    
	override getScope(EObject context, EReference reference){
		findScope(context, reference)
	}
}
