/*
 * generated by Xtext 2.37.0-SNAPSHOT
 */

package eu.extremexp.dsl.scoping

import org.eclipse.xtext.scoping.IScope
import org.eclipse.emf.ecore.EReference
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider
import org.eclipse.emf.ecore.EObject
import org.eclipse.xtext.EcoreUtil2
import org.eclipse.xtext.scoping.Scopes
import eu.extremexp.dsl.xDSL.Root
import com.google.inject.Inject
import org.eclipse.xtext.resource.IResourceDescriptions
import eu.extremexp.dsl.xDSL.AssembledWorkflow
import eu.extremexp.dsl.xDSL.XDSLPackage
import eu.extremexp.dsl.xDSL.DataLink
import eu.extremexp.dsl.xDSL.Data
import eu.extremexp.dsl.xDSL.DataConnection
import eu.extremexp.dsl.xDSL.CompositeWorkflow
import eu.extremexp.dsl.xDSL.Task
import eu.extremexp.dsl.xDSL.TaskSpecification
import eu.extremexp.dsl.xDSL.Workflow
import eu.extremexp.dsl.xDSL.ComponentWithData
import eu.extremexp.dsl.xDSL.TaskConfiguration
import eu.extremexp.dsl.xDSL.ExperimentTaskConfiguraiton
import eu.extremexp.dsl.xDSL.Space
import java.util.HashMap
import org.eclipse.xtext.resource.IEObjectDescription
import org.eclipse.xtext.resource.IResourceDescription

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class XDSLScopeProvider extends AbstractDeclarativeScopeProvider  {
	
//	@Inject
//    IResourceDescriptions resourceDescriptions
    
//    def scopeForAssembledWorkflow(AssembledWorkflow context, EReference reference){
//    	val root = (context.eContainer as Root)
//    	val myPackageName = root.name
//    	// Get all available resources (files) in the workspace
//    	val resolvedWorklfows = root.workflows.filter[it != context].map[it | it as EObject].toList     	
//        resourceDescriptions.allResourceDescriptions.forEach[ resourceDescription |
//        	val workflows = newArrayList()
//        	val packageNames = newArrayList()
//            resourceDescription.exportedObjects.forEach[exportedObject |
//            	if (exportedObject.EClass.name == "Root"){
//            		 packageNames.add(exportedObject.name.toString)
//            	}
//            	if (exportedObject.EClass.name == "CompositeWorkflow" || 
//                		exportedObject.EClass.name == "TaskSpecification" ||
//                		exportedObject.EClass.name == "AssembledWorkflow"  	){
//                
//                	workflows.add(exportedObject)
//                	
//                }
//            ]
//            if (packageNames.size > 0 && packageNames.get(0) == myPackageName){
//            	workflows.forEach[wf |
//            		if (wf.name.lastSegment.toString != context.name.toString){ 
//            			resolvedWorklfows.add(EcoreUtil2.resolve(wf.EObjectOrProxy, context))
//            	     }
//            	]
//            }
//            
//        ]
//        
//        return Scopes.scopeFor(resolvedWorklfows)
//    }
//    
//    def scopeForDataConnectionTasks(DataConnection context, EReference reference){
//    	val myPackageName = (context.eContainer as Root).name
//    	// Get all available resources (files) in the workspace
//    	val resolvedTasks = newArrayList()
//    	 
//        resourceDescriptions.allResourceDescriptions.forEach[ resourceDescription |
//        	val tasks = newArrayList()
//        	val packageNames = newArrayList()
//            resourceDescription.exportedObjects.forEach[exportedObject |
//            	if (exportedObject.EClass.name == "Root"){
//            		 packageNames.add(exportedObject.name.toString)
//            	}
//            	if (exportedObject.EClass.name == "TaskSpecification"){
//                
//                	tasks.add(exportedObject)
//                	
//                }
//            ]
//            if (packageNames.size > 0 && packageNames.get(0) == myPackageName){
//            	tasks.forEach[t |
//            		resolvedTasks.add(EcoreUtil2.resolve(t.EObjectOrProxy, context))
//            	    
//            	]
//            }
//            
//        ]
//        
//        return Scopes.scopeFor(resolvedTasks)
//    }
    
    
    def scopeForConfiguredTasksAndData(DataLink context, CompositeWorkflow container){
    	
    	val resolvedDataPoints = newArrayList()
    	container.eContents.forEach[
    		content	|
    		
    		if (content instanceof TaskConfiguration){
    			resolvedDataPoints.add(EcoreUtil2.resolve(content, context))
    			
    			
    		}
    		
    		if (content instanceof Data){
    			resolvedDataPoints.add(EcoreUtil2.resolve(content, context))
    		}
    	]
    	return Scopes.scopeFor(resolvedDataPoints)
    	
    }
    
    
//    def scopeForConfiguredTaskDataPoints(CompositeWorkflow container, Task task){
//    	val resolvedDataPoints = <Data>newArrayList()
//    	val myPackageName = (container.eContainer as Root).name
//    	container.eContents.forEach[
//    		content	|
//    		
//    		if (content instanceof Task){
//    			if(content.task == task){
//    				resolvedDataPoints += content.inputs
//    				resolvedDataPoints += content.outputs
//    				if (content.primitiveImplementation !== null){
//    					    resourceDescriptions.allResourceDescriptions.forEach[ resourceDescription |
//					        	val tasks = newHashMap
//					        	val packageNames = newArrayList()
//					            resourceDescription.exportedObjects.forEach[exportedObject |
//					            	if (exportedObject.EClass.name == "Root"){
//					            		 packageNames.add(exportedObject.name.toString)
//					            	}
//					            	if (exportedObject.EClass.name == "TaskSpecification"){
//					                	// we look for all the task specified
//					                	tasks.put(exportedObject, resourceDescription)
//					               }
//					               if (exportedObject.EClass.name == "CompositeWorkflow"){
//					                	// we look for all the CompositeWorkflows
//					                	tasks.put(exportedObject, resourceDescription)
//					               }
//					               if (exportedObject.EClass.name == "AssembledWorkflow"){
//					                	// we look for all the AssembledWorkflows
//					                	tasks.put(exportedObject, resourceDescription)
//					               }
//								]
//								tasks.forEach[taskDesc, resource | 
//									var address = content.primitiveImplementation.replace('.', '/')
//									if (resource.URI.path.contains(address)){
//										var workflow = EcoreUtil2.resolve(taskDesc.EObjectOrProxy, container.eContainer) as Workflow
//										resolvedDataPoints += workflow.inputs
//    									resolvedDataPoints += workflow.outputs
//    								}
//    							]
//							]
//							
//						}
//						
//					}
//					
//				}
//				
//			]
//		
//    	return Scopes.scopeFor(resolvedDataPoints)
//    }
    
    
    def scopeForWorkflowData(Workflow wf){
    	var resolvedDataPoints = wf.inputs + wf.outputs
    	return Scopes.scopeFor(resolvedDataPoints)
    }
    
    
	override IScope getScope(EObject context, EReference reference) {
			// Check if we are looking for a Workflow reference
	        if (context instanceof AssembledWorkflow){
		        if (reference == XDSLPackage.Literals.ASSEMBLED_WORKFLOW__PARENT) {
		        	//return scopeForAssembledWorkflow(context, reference)
		        }
			}

			// Find tasks from all parent Workflow s
			if (context instanceof TaskConfiguration){
				if (context.eContainer instanceof AssembledWorkflow){
					var fromCompositeWorkflow = context.eContainer as Workflow
					
					while (!(fromCompositeWorkflow instanceof CompositeWorkflow)){
						fromCompositeWorkflow = ((fromCompositeWorkflow) as AssembledWorkflow).parent
					}
					if (fromCompositeWorkflow instanceof CompositeWorkflow){
						return Scopes.scopeFor(fromCompositeWorkflow.tasks)
					}
				}
			}
			
			// find tasks from all space-workflow connection
			if (context instanceof ExperimentTaskConfiguraiton){
				val space = context.eContainer
				if (space instanceof Space){
					var fromCompositeWorkflow = space.assembledWorkflow as Workflow
					
					while (!(fromCompositeWorkflow instanceof CompositeWorkflow)){
						fromCompositeWorkflow = ((fromCompositeWorkflow) as AssembledWorkflow).parent
					}
					if (fromCompositeWorkflow instanceof CompositeWorkflow){
						return Scopes.scopeFor(fromCompositeWorkflow.tasks)
					}
				}
			}
			
			// If we are looking at data point of a task to use in data link
			if (context instanceof DataLink){
				
				// first, we want to find all the tasks and data in the workflow
		        if (reference == XDSLPackage.Literals.DATA_CONNECTION__REF) {
		        	if (context.eContainer instanceof CompositeWorkflow){
		        		return scopeForConfiguredTasksAndData(context, context.eContainer as CompositeWorkflow)
		        	}
		        }
				
			}
			
			if (context instanceof DataConnection){
		        if (reference == XDSLPackage.Literals.DATA_CONNECTION__REF) {
		        	// if from other workflows, then the data points of the workflow should be returned
		        	if (context.fromComponent){
		        		/*
		        		 * if the data point is accessed by qualified name, we take the parent component and load its data point
		        		 * 2 possibilities
		        		 * 1- from ROOT.pacakge import all (CompositeWorkflow, TaskSpecification, AssembledWorkflow)
		        		 * 2- from task configuration, bring the implementation only
		        		 */
		        		var component = EcoreUtil2.resolve(context.component, context)
		        		if (component instanceof Workflow){
		        			return scopeForWorkflowData(component);
						}
						if (component instanceof Task){
							//return scopeForConfiguredTaskDataPoints(component.eContainer as CompositeWorkflow, component)
						}
		        	}
		        	else{
		        		val dl = context.eContainer
		        		if (dl instanceof DataLink){
		        			val wf = dl.eContainer
			        		if (wf instanceof CompositeWorkflow){ 
				        		// bring local data inputs and outputs
			        			return Scopes.scopeFor(wf.inputs + wf.outputs)
			        		
			        		}
		        		}
		        		
		        		
		        	}
//		        	if (context.task.eContainer instanceof CompositeWorkflow){
//						return scopeForConfiguredTaskDataPoints(context.task.eContainer as CompositeWorkflow, context.task)		        		
//		        	}
		        }
				
			}

	        return super.getScope(context, reference)
	    }
				
				
}


