/*
 * generated by Xtext 2.37.0-SNAPSHOT
 */

package eu.extremexp.dsl.scoping

import org.eclipse.xtext.scoping.IScope
import org.eclipse.emf.ecore.EReference
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider
import org.eclipse.emf.ecore.EObject
import org.eclipse.xtext.EcoreUtil2
import org.eclipse.xtext.scoping.Scopes
import eu.extremexp.dsl.xDSL.Root
import com.google.inject.Inject
import org.eclipse.xtext.resource.IResourceDescriptions
import eu.extremexp.dsl.xDSL.AssembledWorkflow
import eu.extremexp.dsl.xDSL.XDSLPackage
import eu.extremexp.dsl.xDSL.DataLink
import eu.extremexp.dsl.xDSL.Data
import eu.extremexp.dsl.xDSL.DataConnection
import eu.extremexp.dsl.xDSL.CompositeWorkflow
import eu.extremexp.dsl.xDSL.Task
import eu.extremexp.dsl.xDSL.TaskSpecification

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class XDSLScopeProvider extends AbstractDeclarativeScopeProvider  {
	
	@Inject
    IResourceDescriptions resourceDescriptions
    
    def scopeForAssembledWorkflow(AssembledWorkflow context, EReference reference){
    	val myPackageName = (context.eContainer as Root).name
    	// Get all available resources (files) in the workspace
    	val resolvedWorklfows = newArrayList()
    	 
        resourceDescriptions.allResourceDescriptions.forEach[ resourceDescription |
        	val workflows = newArrayList()
        	val packageNames = newArrayList()
            resourceDescription.exportedObjects.forEach[exportedObject |
            	if (exportedObject.EClass.name == "Root"){
            		 packageNames.add(exportedObject.name.toString)
            	}
            	if (exportedObject.EClass.name == "CompositeWorkflow" || 
                		exportedObject.EClass.name == "TaskSpecification" ||
                		exportedObject.EClass.name == "AssembledWorkflow"  	){
                
                	workflows.add(exportedObject)
                	
                }
            ]
            if (packageNames.size > 0 && packageNames.get(0) == myPackageName){
            	workflows.forEach[wf |
            		if (wf.name.lastSegment.toString != context.name.toString){ 
            			resolvedWorklfows.add(EcoreUtil2.resolve(wf.EObjectOrProxy, context))
            	     }
            	]
            }
            
        ]
        
        return Scopes.scopeFor(resolvedWorklfows)
    }
    
    def scopeForDataConnectionTasks(DataConnection context, EReference reference){
    	val myPackageName = (context.eContainer as Root).name
    	// Get all available resources (files) in the workspace
    	val resolvedTasks = newArrayList()
    	 
        resourceDescriptions.allResourceDescriptions.forEach[ resourceDescription |
        	val tasks = newArrayList()
        	val packageNames = newArrayList()
            resourceDescription.exportedObjects.forEach[exportedObject |
            	if (exportedObject.EClass.name == "Root"){
            		 packageNames.add(exportedObject.name.toString)
            	}
            	if (exportedObject.EClass.name == "TaskSpecification"){
                
                	tasks.add(exportedObject)
                	
                }
            ]
            if (packageNames.size > 0 && packageNames.get(0) == myPackageName){
            	tasks.forEach[t |
            		resolvedTasks.add(EcoreUtil2.resolve(t.EObjectOrProxy, context))
            	    
            	]
            }
            
        ]
        
        return Scopes.scopeFor(resolvedTasks)
    }
    
    
    def scopeForConfiguredTasksAndData(DataLink context, CompositeWorkflow container){
    	
    	val resolvedDataPoints = newArrayList()
    	container.eContents.forEach[
    		content	|
    		
    		if (content instanceof Task){
    			if(content.abstract == false){
    				resolvedDataPoints.add(EcoreUtil2.resolve(content.task, context))
    				}
    		}
    		
    		if (content instanceof Data){
    			resolvedDataPoints.add(EcoreUtil2.resolve(content, context))
    		}
    	]
    	return Scopes.scopeFor(resolvedDataPoints)
    	
    }
    
    
    def scopeForConfiguredTaskDataPoints(CompositeWorkflow container, Task task){
    	val resolvedDataPoints = <Data>newArrayList()
    	val myPackageName = (container.eContainer as Root).name
    	container.eContents.forEach[
    		content	|
    		
    		if (content instanceof Task){
    			if(content.abstract == false && content.task == task){
    				resolvedDataPoints += content.inputs
    				resolvedDataPoints += content.outputs
    				if (content.primitiveImplementation !== null){
    					    resourceDescriptions.allResourceDescriptions.forEach[ resourceDescription |
					        	val tasks = newHashMap()
					        	val packageNames = newArrayList()
					            resourceDescription.exportedObjects.forEach[exportedObject |
					            	if (exportedObject.EClass.name == "Root"){
					            		 packageNames.add(exportedObject.name.toString)
					            	}
					            	if (exportedObject.EClass.name == "TaskSpecification"){
					                	// we look for all the task specified
					                	tasks.put(exportedObject, resourceDescription)
					               }
								]
								tasks.forEach[taskDesc, resource | 
									// the following conditions only check if the names are correct
									if (resource.URI.path.replace("/",".").contains(content.primitiveImplementation)){
										var taskSpecification = EcoreUtil2.resolve(taskDesc.EObjectOrProxy, container.eContainer) as TaskSpecification										
										if (taskSpecification.name == content.primitiveImplementation.split("\\.").getLast){
											resolvedDataPoints += taskSpecification.inputs
    										resolvedDataPoints += taskSpecification.outputs
										}
									}
								]
							]
							
						}
						
					}
					
				}
				
			]
				                	
    	return Scopes.scopeFor(resolvedDataPoints)
    }
    
    
	override IScope getScope(EObject context, EReference reference) {
			// Check if we are looking for a Workflow reference
	        if (context instanceof AssembledWorkflow){
		        if (reference == XDSLPackage.Literals.ASSEMBLED_WORKFLOW__PARENT) {
		        	return scopeForAssembledWorkflow(context, reference)
		        }
			}
			
			// If we are looking at data point of a task to use in data link
			if (context instanceof DataLink){
				// first, we want to find all the tasks and data in the workflow
		        if (reference == XDSLPackage.Literals.DATA_CONNECTION__REF ||
		        	reference == XDSLPackage.Literals.DATA_CONNECTION__TASK
		        ) {
		        	if (context.eContainer instanceof CompositeWorkflow){
		        		return scopeForConfiguredTasksAndData(context, context.eContainer as CompositeWorkflow)
		        	}
		        }
				
			}
			
			if (context instanceof DataConnection){
				// first, we want to find all the tasks and data in the workflow
		        if (reference == XDSLPackage.Literals.DATA_CONNECTION__TASK_REF) {
		        	if (context.task.eContainer instanceof CompositeWorkflow){
						return scopeForConfiguredTaskDataPoints(context.task.eContainer as CompositeWorkflow, context.task)		        		
		        	}
		        }
				
			}
//			
//			println ("--------")
//			println (context)
//			println ("--------")
			
//	         Call the super method for other cases
	        return super.getScope(context, reference)
	    }
				
				
}

